<?php

namespace MC\TestBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class MCTestBundle extends Bundle
{
    public function getNamespace()
    {
        return parent::getNamespace(); // TODO: Change the autogenerated stub
    }
}
